<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <NoWarn>$(NoWarn);NU1605</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Duende.IdentityServer" />
    <PackageReference Include="Duende.MultiSpace" />
    <PackageReference Include="Duende.Storage.Sqlite" />
    <PackageReference Include="Duende.Storage" />
    <PackageReference Include="Duende.UserManagement.IdentityServer8" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

</Project>
